
[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
autocmd! BufWritePost,BufEnter * Neomake
let g:neomake_javascript_enabled_makers = ['eslint']
'''

[[plugins]]
repo = 'benjie/neomake-local-eslint.vim'

